// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "./(main)/components/ConvexClientProvider";
import "./globals.css";
import IncomingCall from "./(main)/components/IncomingCall";

export const metadata: Metadata = {
  title: "Brightstar Chat",
  description: "Modern social video communication",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
     signInUrl="/sign-in"
  signUpUrl="/sign-up"
   signInFallbackRedirectUrl="/dashboard"
  signUpFallbackRedirectUrl="/setup-profile"
  >
      <html lang="en">
        <body>
          <ConvexClientProvider>
            {children}
                <IncomingCall />
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}